<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs/Financial/" />
    <Folder Include="Interfaces/Financial/" />
    <Folder Include="Services/Financial/" />
    <Folder Include="DTOs/System/" />
    <Folder Include="Interfaces/System/" />
    <Folder Include="Services/System/" />
    <Folder Include="DTOs/Community/" />
    <Folder Include="Interfaces/Community/" />
    <Folder Include="Services/Community/" />
    <Folder Include="DTOs/Moderation/" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>
</Project>
